rd bin /S /Q 
rd Toggl.Daneel\obj /S /Q 
rd Toggl.Daneel.SiriExtension\obj /S /Q 
rd Toggl.Daneel.SiriExtension.UI\obj /S /Q 
rd Toggl.Daneel.Tests\obj /S /Q 
rd Toggl.Daneel.Tests.UI\obj /S /Q 
rd Toggl.Giskard\obj /S /Q 
rd Toggl.Giskard.Tests\obj /S /Q 
rd Toggl.Giskard.Tests.UI\obj /S /Q 
rd Toggl.Foundation\obj /S /Q 
rd Toggl.Foundation.MvvmCross\obj /S /Q 
rd Toggl.Foundation.Tests\obj /S /Q 
rd Toggl.Multivac\obj /S /Q 
rd Toggl.Multivac.Tests\obj /S /Q 
rd Toggl.PrimeRadiant\obj /S /Q 
rd Toggl.PrimeRadiant.Realm\obj /S /Q 
rd Toggl.PrimeRadiant.Tests\obj /S /Q 
rd Toggl.Ultrawave\obj /S /Q 
rd Toggl.Ultrawave.Tests\obj /S /Q 
rd Toggl.Ultrawave.Tests.Integration\obj /S /Q 
rd Toggl.Tools\SyncDiagramGenerator\obj /S /Q